# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79f988eaf3ef18d0b74bf3b073b05737d129f42893c8366ea74208cff6a19c090c8c81a381b584c4b1a966fd20b84d37e34be96ccfa2410578640c4483d8c632

test:
  secret_key_base: ada027962eeef26b9da72196e7c1dc75f72c201965bfbb85b14610261c952848c20d6f0485a6316322ef7138ad9b42cae55b41942c451ed90f839c02fe0ba800

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
