require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StripesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Stripe. As you add validations to Stripe, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StripesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all stripes as @stripes" do
      stripe = Stripe.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:stripes)).to eq([stripe])
    end
  end

  describe "GET #show" do
    it "assigns the requested stripe as @stripe" do
      stripe = Stripe.create! valid_attributes
      get :show, {:id => stripe.to_param}, valid_session
      expect(assigns(:stripe)).to eq(stripe)
    end
  end

  describe "GET #new" do
    it "assigns a new stripe as @stripe" do
      get :new, {}, valid_session
      expect(assigns(:stripe)).to be_a_new(Stripe)
    end
  end

  describe "GET #edit" do
    it "assigns the requested stripe as @stripe" do
      stripe = Stripe.create! valid_attributes
      get :edit, {:id => stripe.to_param}, valid_session
      expect(assigns(:stripe)).to eq(stripe)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Stripe" do
        expect {
          post :create, {:stripe => valid_attributes}, valid_session
        }.to change(Stripe, :count).by(1)
      end

      it "assigns a newly created stripe as @stripe" do
        post :create, {:stripe => valid_attributes}, valid_session
        expect(assigns(:stripe)).to be_a(Stripe)
        expect(assigns(:stripe)).to be_persisted
      end

      it "redirects to the created stripe" do
        post :create, {:stripe => valid_attributes}, valid_session
        expect(response).to redirect_to(Stripe.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved stripe as @stripe" do
        post :create, {:stripe => invalid_attributes}, valid_session
        expect(assigns(:stripe)).to be_a_new(Stripe)
      end

      it "re-renders the 'new' template" do
        post :create, {:stripe => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested stripe" do
        stripe = Stripe.create! valid_attributes
        put :update, {:id => stripe.to_param, :stripe => new_attributes}, valid_session
        stripe.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested stripe as @stripe" do
        stripe = Stripe.create! valid_attributes
        put :update, {:id => stripe.to_param, :stripe => valid_attributes}, valid_session
        expect(assigns(:stripe)).to eq(stripe)
      end

      it "redirects to the stripe" do
        stripe = Stripe.create! valid_attributes
        put :update, {:id => stripe.to_param, :stripe => valid_attributes}, valid_session
        expect(response).to redirect_to(stripe)
      end
    end

    context "with invalid params" do
      it "assigns the stripe as @stripe" do
        stripe = Stripe.create! valid_attributes
        put :update, {:id => stripe.to_param, :stripe => invalid_attributes}, valid_session
        expect(assigns(:stripe)).to eq(stripe)
      end

      it "re-renders the 'edit' template" do
        stripe = Stripe.create! valid_attributes
        put :update, {:id => stripe.to_param, :stripe => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested stripe" do
      stripe = Stripe.create! valid_attributes
      expect {
        delete :destroy, {:id => stripe.to_param}, valid_session
      }.to change(Stripe, :count).by(-1)
    end

    it "redirects to the stripes list" do
      stripe = Stripe.create! valid_attributes
      delete :destroy, {:id => stripe.to_param}, valid_session
      expect(response).to redirect_to(stripes_url)
    end
  end

end
